name: Java CI with Maven and MySQL

on:
  push:
    branches: [ "panier" ]
  pull_request:
    branches: [ "panier" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456789yassmine
          MYSQL_DATABASE: devops_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..30}; do
            nc -z 127.0.0.1 3306 && echo "MySQL is up!" && break
            echo "Waiting for MySQL..." && sleep 2
          done

      - name: Create tables
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword db_users <schema_panier.sql

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
